[[Preparation]]
## Preparation

This section describes what, how, and where to install the software needed for this lab.

### Hardware
Operating System: Windows 7 (SP1), Mac OS X (10.8 or later), Fedora (21 or later)
Memory: At least 4 GB+, preferred 8 GB

### Software

. Java: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u45 or later]
. Web Browser
.. https://www.google.com/chrome/browser/desktop/[Chrome]
.. link:http://www.getfirefox.com[Firefox]
.. http://wildfly.org/downloads/[WildFly 10.0.0.Final]
.. http://www.eclipse.org/downloads/[Eclipse] (or IDE of choice)

### Maven

. Download Apache Maven...
.. from Internet: https://maven.apache.org/download.cgi
. Unzip to a directory of your choice and add it to the `PATH`.

### Install WildFly
WildFly 10 is the latest release in a series of JBoss open-source application server offerings.  WildFly 10 is an exceptionally fast, lightweight and powerful implementation of the Java Enterprise Edition 7 Platform specifications.  The state-of-the-art architecture built on the Modular Service Container enables services on-demand when your application requires them.

Simply extract your chosen download to the directory of your choice (we call it +%JBOSS_HOME+). You can install WildFly 10 on any operating system that supports the zip or tar formats. Refer to the Release Notes for additional information related to the release.

To start WildFly 10 using the default web profile configuration in "standalone" mode, change directory to $JBOSS_HOME/bin.

[source, console]
----
./standalone.sh
----

As with previous WildFly releases, you can point your browser to http://localhost:8080 (if using the default configured http port) which brings you to the Welcome Screen:

If you run into problems, refer to the complete  https://docs.jboss.org/author/display/WFLY10/Getting+Started+Guide[getting started guide and verify] that you completed all necessary steps.
